StructType(
    StructField("controller",StringType,true),
    StructField("cluster_id",StringType,true),
    StructField("cluster_data",
        StructType(
            StructField("created_at",LongType,true),
            StructField("vertical",StringType,true),
            StructField("cluster_configs",
                ArrayType(
                    StructType(
                        StructField("cluster_params",
                            StructType(
                                StructField("common_params",
                                    StructType(
                                        StructField("flavors",ArrayType(StringType,true),true),
                                        StructField("flavour_versions",ArrayType(StringType,true),true),
                                        StructField("traffics",
                                            ArrayType(
                                                StructType(
                                                    StructField("traffic_source",StringType,true),
                                                    StructField("traffic_medium",StringType,true),
                                                    StructField("traffic_country_id",StringType,true),
                                                    StructField("traffic_city_id",StringType,true)
                                                ),true
                                            ),true
                                        ),
                                        StructField("is_include_segments",BooleanType,true),
                                        StructField("user_segments",ArrayType(StringType,true),true),
                                        StructField("session_types",ArrayType(StringType,true),true),
                                        StructField("countries",ArrayType(StringType,true),true)
                                    ),true
                                ),
                                StructField("ab_discount_configs",
                                    ArrayType(
                                        StructType(
                                            StructField("config_id",StringType,true),
                                            StructField("traffic_splits",
                                                ArrayType(
                                                    StructType(
                                                        StructField("min",LongType,true), StructField("max",LongType,true)
                                                    ),true
                                                ),true
                                            ),
                                            StructField("discount_params",
                                                StructType(
                                                    StructField("method",StringType,true),
                                                    StructField("discount_option",
                                                        StructType(
                                                            StructField("nm_options",
                                                                StructType(
                                                                    StructField("value",DoubleType,true),
                                                                    StructField("percentage_cap",
                                                                        StructType(
                                                                            StructField("min",LongType,true),
                                                                            StructField("max",LongType,true)
                                                                        ),true
                                                                    )
                                                                ),true
                                                            ),
                                                            StructField("flat_options",
                                                                StructType(
                                                                    StructField("discount_type",StringType,true),
                                                                    StructField("value",DoubleType,true),
                                                                    StructField("percentage_cap",
                                                                        StructType(
                                                                            StructField("min",LongType,true),
                                                                            StructField("max",LongType,true)
                                                                        ),true
                                                                    )
                                                                ),true
                                                            )
                                                        ),true
                                                    )
                                                ),true
                                            )
                                        ),true
                                    ),true
                                ),
                                StructField("entity_params",
                                    StructType(
                                        StructField("hotels",
                                            StructType(
                                                StructField("check_ins",
                                                    ArrayType(
                                                        StructType(
                                                            StructField("min",LongType,true),
                                                            StructField("max",LongType,true)
                                                        ),true
                                                    ),true
                                                ),
                                                StructField("room_nights",
                                                    ArrayType(
                                                        StructType(
                                                            StructField("min",LongType,true),
                                                            StructField("max",LongType,true)
                                                        ),true
                                                    ),true
                                                ),
                                                StructField("grand_totals",
                                                    ArrayType(
                                                        StructType(
                                                            StructField("min",LongType,true),
                                                            StructField("max",LongType,true)
                                                        ),true
                                                    ),true
                                                ),
                                                StructField("pay_modes",ArrayType(StringType,true),true),
                                                StructField("tags",ArrayType(StringType,true),true),
                                                StructField("vendors",
                                                    StructType(
                                                        StructField("gi_vendors",
                                                            StructType(
                                                                StructField("vendors",ArrayType(StringType,true),true)
                                                            ),true
                                                        ),
                                                        StructField("mmt_vendors",
                                                            StructType(
                                                                StructField("vendors",ArrayType(StringType,true),true)
                                                            ),true
                                                        )
                                                    ),true
                                                )
                                            ),true
                                        )
                                    ),true
                                )
                            ),true
                        ),
                        StructField("cluster_id",StringType,true),
                        StructField("promocodes",ArrayType(StringType,true),true),
                        StructField("entities",
                            StructType(
                                StructField("hotels",
                                    StructType(
                                        StructField("ids",ArrayType(LongType,true),true)
                                    ),true
                                )
                            ),true
                        ),
                        StructField("discount_type",StringType,true)
                    ),true
                ),true
            ),
            StructField("delta_params",
                ArrayType(
                    StructType(
                        StructField("common_params",
                            StructType(
                                StructField("flavors",ArrayType(StringType,true),true),
                                StructField("flavour_versions",ArrayType(StringType,true),true),
                                StructField("traffics",
                                    ArrayType(
                                        StructType(
                                            StructField("traffic_source",StringType,true),
                                            StructField("traffic_medium",StringType,true),
                                            StructField("traffic_country_id",StringType,true),
                                            StructField("traffic_city_id",StringType,true)
                                        ),true
                                    ),true
                                ),
                                StructField("is_include_segments",BooleanType,true),
                                StructField("user_segments",ArrayType(StringType,true),true),
                                StructField("session_types",ArrayType(StringType,true),true),
                                StructField("countries",ArrayType(StringType,true),true)
                            ),true
                        ),
                        StructField("ab_discount_configs",
                            ArrayType(
                                StructType(
                                    StructField("config_id",StringType,true),
                                    StructField("traffic_splits",
                                        ArrayType(
                                            StructType(
                                                StructField("min",LongType,true),
                                                StructField("max",LongType,true)
                                            ),true
                                        ),true
                                    ),
                                    StructField("discount_params",
                                        StructType(
                                            StructField("method",StringType,true),
                                            StructField("discount_option",
                                                StructType(
                                                    StructField("nm_options",
                                                        StructType(
                                                            StructField("value",DoubleType,true),
                                                            StructField("percentage_cap",
                                                                StructType(
                                                                    StructField("min",LongType,true),
                                                                    StructField("max",LongType,true)
                                                                ),true
                                                            )
                                                        ),true
                                                    ),
                                                    StructField("flat_options",
                                                        StructType(
                                                            StructField("discount_type",StringType,true),
                                                            StructField("value",DoubleType,true),
                                                            StructField("percentage_cap",
                                                                StructType(
                                                                    StructField("min",LongType,true),
                                                                    StructField("max",LongType,true)
                                                                ),true
                                                            )
                                                        ),true
                                                    )
                                                ),true
                                            )
                                        ),true
                                    )
                                ),true
                            ),true
                        ),
                        StructField("entity_params",
                                    StructType(
                                        StructField("hotels",
                                            StructType(
                                                StructField("check_ins",
                                                    ArrayType(
                                                        StructType(
                                                            StructField("min",LongType,true),
                                                            StructField("max",LongType,true)
                                                        ),true
                                                    ),true
                                                ),
                                                StructField("room_nights",
                                                    ArrayType(
                                                        StructType(
                                                            StructField("min",LongType,true),
                                                            StructField("max",LongType,true)
                                                        ),true
                                                    ),true
                                                ),
                                                StructField("grand_totals",
                                                    ArrayType(
                                                        StructType(
                                                            StructField("min",LongType,true),
                                                            StructField("max",LongType,true)
                                                        ),true
                                                    ),true
                                                ),
                                                StructField("pay_modes",ArrayType(StringType,true),true),
                                                StructField("tags",ArrayType(StringType,true),true),
                                                StructField("vendors",
                                                    StructType(
                                                        StructField("gi_vendors",
                                                            StructType(
                                                                StructField("vendors",ArrayType(StringType,true),true)
                                                            ),true
                                                        ),
                                                        StructField("mmt_vendors",
                                                            StructType(
                                                                StructField("vendors",ArrayType(StringType,true),true)
                                                            ),true
                                                        )
                                                    ),true
                                                )
                                            ),true
                                        )
                                    ),true
                        )
                    ),true
                ),true
            ),
            StructField("priority",LongType,true),
            StructField("org",StringType,true)
        ),true
    ),
    StructField("delta_applied",
        ArrayType(
            StructType(
                StructField("delta_id",StringType,true),
                StructField("value",DoubleType,true)
            ),true
        ),true
    ),
    StructField("priority",IntegerType,true),
    StructField("vertical",StringType,true),
    StructField("category_group",StringType,true),
    StructField("focus",StringType,true)
)